=== kourosh-ebinj/linkedin-xml/xml/Data/Data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- Root element -->
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" type="BookType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Book complex type -->
  <xs:complexType name="BookType">
    <xs:sequence>
      <xs:element name="author" type="xs:string"/>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="genre" type="xs:string"/>
      <xs:element name="price" type="PriceType"/>
      <xs:element name="publish_date" type="xs:date"/>
      <xs:element name="description" type="xs:string"/>
	  <xs:element name="custom_code" type="xs:string" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="BookIdType" use="required"/>
  </xs:complexType>

  <!-- Price with 2 fractional digits (e.g., 44.95) -->
  <xs:simpleType name="PriceType">
    <xs:restriction base="xs:decimal">
      <xs:totalDigits value="6"/>
      <xs:fractionDigits value="2"/>
      <xs:minInclusive value="0.00"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Book ID like 'bk101' -->
  <xs:simpleType name="BookIdType">
    <xs:restriction base="xs:int">
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== kourosh-ebinj/linkedin-xml/xml/Data/Data.xml
<?xml version="1.0" encoding="utf-8" ?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Data.xsd">	
	<book id="100">
		<author>Gambardella, Matthew</author>
		<title>XML Developer's Guide</title>
		<genre>Computer</genre>
		<price>44.95</price>
		<publish_date>2000-10-01</publish_date>
		<description>
			An in-depth look at creating applications
			with XML.
		</description>
		<custom_code><![CDATA[ <script> if (a < b) alert("Hi") </script> ]]></custom_code>
	</book>
	<book id="101">
		<author>Ralls, Kim</author>
		<title>Midnight Rain</title>
		<genre>Fantasy</genre>
		<price>5.95</price>
		<publish_date>2000-12-16</publish_date>
		<description>
			A former architect battles corporate zombies,
			an evil sorceress, and her own childhood to become queen
			of the world.
		</description>
	</book>
	<book id="102">
		<author>Corets, Eva</author>
		<title>Maeve Ascendant</title>
		<genre>Fantasy</genre>
		<price>5.95</price>
		<publish_date>2000-11-17</publish_date>
		<description>
			After the collapse of a nanotechnology
			society in England, the young survivors lay the
			foundation for a new society.
		</description>
	</book>
	<book id="103">
		<author>Corets, Eva</author>
		<title>Oberon's Legacy</title>
		<genre>Fantasy</genre>
		<price>5.95</price>
		<publish_date>2001-03-10</publish_date>
		<description>
			In post-apocalypse England, the mysterious
			agent known only as Oberon helps to create a new life
			for the inhabitants of London. Sequel to Maeve
			Ascendant.
		</description>
	</book>
	<book id="104">
		<author>Corets, Eva</author>
		<title>The Sundered Grail</title>
		<genre>Fantasy</genre>
		<price>5.95</price>
		<publish_date>2001-09-10</publish_date>
		<description>
			The two daughters of Maeve, half-sisters,
			battle one another for control of England. Sequel to
			Oberon's Legacy.
		</description>
	</book>
	<book id="105">
		<author>Randall, Cynthia</author>
		<title>Lover Birds</title>
		<genre>Romance</genre>
		<price>4.95</price>
		<publish_date>2000-09-02</publish_date>
		<description>
			When Carla meets Paul at an ornithology
			conference, tempers fly as feathers get ruffled.
		</description>
	</book>
	<book id="106">
		<author>Thurman, Paula</author>
		<title>Splish Splash</title>
		<genre>Romance</genre>
		<price>4.95</price>
		<publish_date>2000-11-02</publish_date>
		<description>
			A deep sea diver finds true love twenty
			thousand leagues beneath the sea.
		</description>
	</book>
	<book id="107">
		<author>Knorr, Stefan</author>
		<title>Creepy Crawlies</title>
		<genre>Horror</genre>
		<price>4.95</price>
		<publish_date>2000-12-06</publish_date>
		<description>
			An anthology of horror stories about roaches,
			centipedes, scorpions  and other insects.
		</description>
	</book>
	<book id="108">
		<author>Kress, Peter</author>
		<title>Paradox Lost</title>
		<genre>Science Fiction</genre>
		<price>6.95</price>
		<publish_date>2000-11-02</publish_date>
		<description>
			After an inadvertant trip through a Heisenberg
			Uncertainty Device, James Salway discovers the problems
			of being quantum.
		</description>
	</book>
	<book id="109">
		<author>O'Brien, Tim</author>
		<title>Microsoft .NET: The Programming Bible</title>
		<genre>Computer</genre>
		<price>36.95</price>
		<publish_date>2000-12-09</publish_date>
		<description>
			Microsoft's .NET initiative is explored in
			detail in this deep programmer's reference.
		</description>
	</book>
	<book id="110">
		<author>O'Brien, Tim</author>
		<title>MSXML3: A Comprehensive Guide</title>
		<genre>Computer</genre>
		<price>36.95</price>
		<publish_date>2000-12-01</publish_date>
		<description>
			The Microsoft MSXML3 parser is covered in
			detail, with attention to XML DOM interfaces, XSLT processing,
			SAX and more.
		</description>
	</book>
	<book id="111">
		<author>Galos, Mike</author>
		<title>Visual Studio 7: A Comprehensive Guide</title>
		<genre>Computer</genre>
		<price>49.95</price>
		<publish_date>2001-04-16</publish_date>
		<description>
			Microsoft Visual Studio 7 is explored in depth,
			looking at how Visual Basic, Visual C++, C#, and ASP+ are
			integrated into a comprehensive development
			environment.
		</description>
	</book>
</catalog>
